// French -> Spanish dictionary + grammar logic, ported from the desktop app
// (src/dictionary.py and src/grammar.py) so behavior matches exactly.

// ---- normalize (accent folding) --------------------------------------------
const _ACCENTS = {
  "à": "a", "â": "a", "ä": "a", "æ": "ae", "ç": "c",
  "é": "e", "è": "e", "ê": "e", "ë": "e",
  "î": "i", "ï": "i", "ô": "o", "œ": "oe",
  "ù": "u", "û": "u", "ü": "u", "ÿ": "y",
};
function normalize(word) {
  return String(word).toLowerCase()
    .replace(/[’']/g, "'")
    .replace(/[àâäæçéèêëîïôœùûüÿ]/g, (c) => _ACCENTS[c] || c);
}

// ---- curated function words + high-frequency vocab (port of _CURATED) -----
const _CURATED = {
  "le": "el / lo", "la": "la", "les": "los / las", "un": "un / uno",
  "une": "una", "des": "unos / unas", "du": "del", "de": "de", "et": "y",
  "ou": "o / u", "que": "que", "qui": "que / quien", "dont": "cuyo",
  "au": "al", "aux": "a los / a las", "en": "en", "dans": "en / dentro de",
  "sur": "sobre", "sous": "bajo", "avec": "con", "sans": "sin",
  "pour": "para", "par": "por", "à": "a / en", "il": "él",
  "elle": "ella", "ils": "ellos", "elles": "ellas", "je": "yo",
  "tu": "tú", "nous": "nosotros", "vous": "ustedes", "on": "se",
  "se": "se", "ne": "no", "pas": "no", "est": "es / está",
  "sont": "son", "était": "era / estaba", "être": "ser / estar",
  "a": "ha / tiene", "avait": "tenía / había", "ont": "tienen / han",
  "avoir": "tener / haber", "fait": "hecho / hace", "faire": "hacer",
  "dit": "dijo", "dire": "decir", "parle": "habla", "parler": "hablar",
  "voit": "ve", "voir": "ver", "vint": "vino", "venait": "venía",
  "prend": "toma", "prendre": "tomar / coger", "vient": "viene",
  "venir": "venir", "va": "va", "aller": "ir", "allait": "iba",
  "me": "me", "te": "te", "lui": "le / él", "leur": "su / les",
  "moi": "mí", "toi": "tí", "vers": "hacia", "chez": "en casa de",
  "depuis": "desde", "pendant": "durante", "avant": "antes",
  "après": "después", "entre": "entre", "selon": "según",
  "contre": "contra", "car": "porque", "mais": "pero", "donc": "así que",
  "si": "si", "bien": "bien", "très": "muy", "plus": "más",
  "moins": "menos", "tout": "todo", "toute": "toda", "tous": "todos",
  "toutes": "todas", "ce": "este / eso", "cette": "esta",
  "ces": "estos / estas", "son": "su (de él)", "sa": "su (de ella)",
  "ses": "sus", "mon": "mi", "ma": "mi", "mes": "mis", "ton": "tu",
  "ta": "tu", "tes": "tus", "notre": "nuestro", "nos": "nuestros",
  "votre": "su / vuestro", "leurs": "sus", "y": "allí",
  "où": "donde", "quand": "cuando", "combien": "cuánto",
  "quel": "cuál", "quelle": "cuál", "quels": "cuáles", "quelles": "cuáles",
  "seul": "solo", "seule": "sola", "grand": "grande", "grande": "grande",
  "petit": "pequeño", "petite": "pequeña", "bon": "bueno",
  "bonne": "buena", "mauvais": "malo", "premier": "primero",
  "dernier": "último", "même": "mismo / incluso", "autre": "otro",
  "chacun": "cada uno", "chose": "cosa", "homme": "hombre",
  "femme": "mujer", "enfant": "niño", "peuple": "pueblo", "vie": "vida",
  "mort": "muerte", "ciel": "cielo", "terre": "tierra", "eau": "agua",
  "feu": "fuego", "lumière": "luz", "ténèbres": "tinieblas", "jour": "día",
  "nuit": "noche", "soleil": "sol", "lune": "luna", "étoile": "estrella",
  "vent": "viento", "pluie": "lluvia", "montagne": "montaña", "mer": "mar",
  "roi": "rey", "reine": "reina", "prêtre": "sacerdote",
  "prophète": "profeta", "ange": "ángel", "diable": "diablo",
  "esprit": "espíritu", "âme": "alma", "cœur": "corazón",
  "parole": "palabra", "voix": "voz", "nom": "nombre", "livre": "libro",
  "ville": "ciudad", "maison": "casa", "porte": "puerta", "pain": "pan",
  "vin": "vino", "poisson": "pescado", "agneau": "cordero",
  "brebis": "oveja", "peur": "miedo", "amour": "amor", "paix": "paz",
  "joie": "alegría", "grâce": "gracia", "foi": "fe", "espoir": "esperanza",
  "vérité": "verdad", "mensonge": "mentira", "voie": "camino / vía",
  "chemin": "camino", "maître": "maestro", "serviteur": "sirviente",
  "Dieu": "Dios", "Seigneur": "Señor", "Christ": "Cristo",
  "Jésus": "Jesús", "frère": "hermano", "sœur": "hermana",
  "père": "padre", "mère": "madre", "fils": "hijo", "fille": "hija",
  "famille": "familia", "ami": "amigo", "ennemi": "enemigo",
  "yeux": "ojos", "main": "mano", "pied": "pie", "tête": "cabeza",
  "bouche": "boca", "oreille": "oreja", "montagne": "montaña",
  "porte": "puerta", "peuple": "pueblo", "chose": "cosa",
};

// Common French verb infinitives -> Spanish (port of _COMMON_VERBS).
const _COMMON_VERBS = {
  "être": "ser / estar", "avoir": "tener / haber", "faire": "hacer",
  "aller": "ir", "venir": "venir", "voir": "ver",
  "dire": "decir", "parler": "hablar", "aimer": "amar / querer",
  "donner": "dar", "prendre": "tomar / coger", "mettre": "poner / meter",
  "trouver": "encontrar", "croire": "creer", "savoir": "saber",
  "pouvoir": "poder", "vouloir": "querer", "devoir": "deber",
  "falloir": "hacer falta / tener que", "entendre": "oír",
  "écouter": "escuchar", "regarder": "mirar", "chercher": "buscar",
  "demander": "pedir / preguntar", "répondre": "responder",
  "penser": "pensar", "connaître": "conocer",
  "arriver": "llegar / suceder", "partir": "partir / irse",
  "sortir": "salir", "rentrer": "volver a casa", "rester": "quedarse",
  "revenir": "volver", "devenir": "convertirse", "mourir": "morir",
  "vivre": "vivir", "naître": "nacer", "manger": "comer", "boire": "beber",
  "dormir": "dormir", "habiter": "habitar / vivir", "travailler": "trabajar",
  "adorer": "adorar", "prier": "orar / rezar", "bénir": "bendecir",
  "louer": "alabar / alquilar", "chanter": "cantar", "créer": "crear",
  "multiplier": "multiplicar", "diviser": "dividir", "recevoir": "recibir",
  "envoyer": "enviar", "porter": "llevar",
  "apporter": "traer", "amener": "llevar / traer", "suivre": "seguir",
  "tenir": "tener / sostener", "garder": "guardar", "protéger": "proteger",
  "sauver": "salvar", "libérer": "liberar", "délivrer": "liberar",
  "commander": "mandar", "obéir": "obedecer", "appeler": "llamar",
  "nommer": "nombrar", "choisir": "elegir", "recommencer": "volver a empezar",
  "commencer": "empezar", "finir": "terminar", "continuer": "continuar",
  "cesser": "cesar / dejar de", "retourner": "volver / devolver",
  "rendre": "devolver", "vendre": "vender", "acheter": "comprar",
  "ouvrir": "abrir", "fermer": "cerrar", "écrire": "escribir",
  "lire": "leer", "compter": "contar",
  "mesurer": "medir", "peser": "pesar", "couper": "cortar",
  "raser": "derribar / arrasar", "bâtir": "edificar", "construire": "construir",
  "détruire": "destruir", "casser": "romper", "cacher": "esconder",
  "montrer": "mostrar", "expliquer": "explicar", "enseigner": "enseñar",
  "apprendre": "aprender", "comprendre": "comprender / entender",
  "payer": "pagar", "coûter": "costar", "valoir": "valer",
  "mériter": "merecer", "gagner": "ganar", "perdre": "perder",
  "attendre": "esperar", "espérer": "esperar / tener esperanza", "souffrir": "sufrir",
  "pleurer": "llorar", "rire": "reír", "sourire": "sonreír",
  "danser": "bailar", "marcher": "caminar",
  "courir": "correr", "voler": "volar / robar", "tomber": "caer",
  "lever": "levantar", "monter": "subir", "descendre": "bajar",
  "entrer": "entrar", "rejoindre": "unirse / alcanzar",
  "accompagner": "acompañar", "quitter": "dejar / salir de",
  "laisser": "dejar", "abandonner": "abandonar", "oublier": "olvidar",
  "se souvenir": "acordarse", "mener": "llevar / guiar",
  "guider": "guiar", "diriger": "dirigir", "gouverner": "gobernar",
  "régner": "reinar", "juger": "juzgar", "condamner": "condenar",
  "pardonner": "perdonar", "aider": "ayudar", "servir": "servir",
  "utiliser": "usar", "manquer": "faltar / echar de menos",
  "jouer": "jugar", "pêcher": "pecar / pescar",
  "semer": "sembrar", "récolter": "cosechar",
  "moissonner": "cosechar", "labourer": "arar", "planter": "plantar",
  "arroser": "regar", "couler": "fluir / correr (líquido)",
  "brûler": "quemar / arder", "éteindre": "apagar", "allumer": "encender",
  "éclairer": "iluminar", "briller": "brillar", "luire": "brillar",
  "se lever": "levantarse", "éveiller": "despertar", "réveiller": "despertar",
  "se repentir": "arrepentirse", "se convertir": "convertirse",
  "s'approcher": "acercarse", "s'éloigner": "alejarse",
  "s'asseoir": "sentarse", "se coucher": "acostarse", "se taire": "callarse",
  "se rencontrer": "encontrarse",
  "constater": "constatar / comprobar",
  "séparer": "separar", "réaliser": "realizar / darse cuenta",
  "rassembler": "reunir", "ajouter": "añadir", "placer": "colocar / poner",
  "produire": "producir", "paraître": "aparecer", "paraitre": "aparecer",
  "apparaître": "aparecer", "pousser": "crecer / empujar",
  "présider": "presidir", "déterminer": "determinar",
  "mouvoir": "mover", "peupler": "poblar", "siéger": "sentarse",
  "couvrir": "cubrir", "déplacer": "mover / desplazar",
  "s'envoler": "alzar el vuelo / volar", "envoler": "alzar el vuelo / volar",
  "dominer": "dominar", "envahir": "invadir", "recouvrir": "cubrir",
  "envelopper": "envolver", "faufiler": "deslizarse / colarse",
  "déclarer": "declarar", "ordonner": "ordenar / mandar",
  "commettre": "cometer", "offrir": "ofrecer", "passer": "pasar",
  "annoncer": "anunciar", "tuer": "matar", "obtenir": "obtener / conseguir",
  "attaquer": "atacar", "accorder": "otorgar / conceder",
  "conduire": "conducir / guiar", "agir": "actuar",
  "affirmer": "afirmar", "situer": "situar / ubicar",
  "signifier": "significar", "consulter": "consultar",
  "accomplir": "cumplir / realizar", "livrer": "entregar",
  "jeter": "arrojar / echar", "écrier": "exclamar (s'écrier)",
  "décider": "decidir", "appartenir": "pertenecer",
  "emporter": "llevarse", "entreprendre": "emprender",
  "sacrifier": "sacrificar", "craindre": "temer",
  "arrêter": "detener / parar", "entourer": "rodear",
  "traverser": "atravesar", "frapper": "golpear",
  "poursuivre": "perseguir", "reprendre": "retomar / reprender",
  "désigner": "designar / señalar", "consacrer": "consagrar",
  "purifier": "purificar", "sanctifier": "santificar",
  "guérir": "sanar / curar",
  "explorer": "explorar", "répartir": "repartir / distribuir",
  "enlever": "quitar / llevar", "transporter": "transportar",
  "planifier": "planificar", "fixer": "fijar",
  "présenter": "presentar", "combattre": "combatir",
  "désirer": "desear", "jurer": "jurar", "laver": "lavar",
  "échapper": "escapar", "disparaître": "desaparecer",
  "déplaire": "desagradar", "plaire": "placer / gustar",
  "réserver": "reservar", "adresser": "dirigir / enviar",
  "épouser": "casarse con / desposar",
  "destiner": "destinar / designar", "enterrer": "enterrar",
  "succéder": "suceder", "refuser": "rechazar",
  "nourrir": "alimentar / nutrir", "communiquer": "comunicar",
  "raconter": "contar / relatar", "respecter": "respetar",
  "crier": "gritar", "battre": "batir / golpear",
  "atteindre": "alcanzar", "établir": "establecer",
  "traiter": "tratar", "installer": "instalar",
  "coucher": "acostar / recostar", "prononcer": "pronunciar",
  "célébrer": "celebrar", "reconnaître": "reconocer",
  "manifester": "manifestar / mostrar", "approcher": "acercar",
  "remettre": "volver a poner / entregar", "permettre": "permitir",
  "préparer": "preparar", "révéler": "revelar",
  "convoquer": "convocar", "saisir": "agarrar / apoderarse de",
  "remplir": "llenar", "concerner": "concernir / atañer",
  "chasser": "cazar / expulsar", "proclamer": "proclamar",
  "exterminer": "exterminar", "fabriquer": "fabricar",
  "supporter": "soportar / aguantar", "transmettre": "transmitir",
  "changer": "cambiar", "ramener": "traer de vuelta",
  "emparer": "apoderarse (s'emparer)", "intituler": "titular (intitulé = titulado)",
  "enfuir": "huir (s'enfuir = huirse)",
  "posséder": "poseer", "détester": "odiar / detestar",
  "renoncer": "renunciar", "confier": "confiar / encomendar",
  "poser": "colocar / plantear", "déposer": "depositar / dejar",
  "dresser": "erigir / levantar", "emmener": "llevar / conducir",
  "réfugier": "refugiar (se réfugier = refugiarse)",
  "effectuer": "realizar / efectuar", "tirer": "tirar / sacar",
  "pénétrer": "penetrar", "demeurer": "morar / permanecer",
  "soumettre": "someter", "rejeter": "rechazar / desechar",
  "intervenir": "intervenir", "résister": "resistir",
  "suffire": "bastar", "convenir": "convenir / corresponder",
  "s'incliner": "inclinarse", "achever": "terminar / rematar",
  "étendre": "extender", "exécuter": "ejecutar",
  "tourner": "girar / dar la vuelta", "venger": "vengar",
  "envoyer": "enviar",
  "s'asseoir": "sentarse", "considérer": "considerar",
  "ressembler": "parecerse", "conclure": "concluir",
  "disperser": "dispersar", "circoncire": "circuncidar",
  "subir": "experimentar / someterse a", "punir": "castigar",
  "fournir": "proveer / suministrar", "relever": "levantar / alzar",
  "supplier": "implorar / rogar", "remercier": "agradecer",
  "désobéir": "desobedecer", "participer": "participar",
  "tromper": "engañar",
  "vanter": "alabar / jactarse (se vanter)", "répliquer": "replicar / responder",
};

// Common French nouns -> Spanish (port of _COMMON_NOUNS).
const _COMMON_NOUNS = {
  "commencement": "comienzo / principio", "forme": "forma",
  "obscurité": "oscuridad", "abîme": "abismo", "océan": "océano",
  "surface": "superficie", "eau": "agua", "voûte": "bóveda",
  "fête": "fiesta", "année": "año", "source": "fuente / manantial",
  "étoile": "estrella", "monstre": "monstruo", "animal": "animal",
  "bête": "bestia / animal", "enfant": "niño / hijo", "oisau": "pájaro",
  "oiseau": "pájaro / ave", "graine": "semilla", "pépin": "pepita",
  "noyau": "hueso / núcleo", "semence": "semilla", "fruit": "fruto",
  "arbre": "árbol", "herbe": "hierba", "plante": "planta",
  "mois": "mes", "jour": "día", "soir": "tarde / noche", "matin": "mañana",
  "lumière": "luz", "mère": "madre", "père": "padre", "frère": "hermano",
  "sœur": "hermana", "fils": "hijo", "fille": "hija", "famille": "familia",
  "créature": "criatura", "être": "ser", "espèce": "especie",
  "terre": "tierra", "peuple": "pueblo", "tribu": "tribu",
  "nation": "nación", "roi": "rey", "temple": "templo", "autel": "altar",
  "sacrifice": "sacrificio", "péché": "pecado", "salut": "salvación",
  "promesse": "promesa", "alliance": "alianza", "loi": "ley",
  "prophétie": "profecía", "évangile": "evangelio", "apôtre": "apóstol",
  "église": "iglesia", "parole": "palabra", "Dieu": "Dios",
  "ciel": "cielo", "mer": "mar", "rivière": "río", "désert": "desierto",
  "montagne": "montaña", "colline": "colina", "vallée": "valle",
  "pierre": "piedra", "rocher": "roca", "or": "oro", "argent": "plata",
  "fer": "hierro", "cuivre": "cobre", "blé": "trigo", "pain": "pan",
  "haut": "altura / alto", "os": "hueso", "sang": "sangre",
  "corps": "cuerpo", "esprit": "espíritu", "crainte": "temor",
  "espérance": "esperanza", "chagrin": "tristeza", "force": "fuerza",
  "sagesse": "sabiduría", "connaissance": "conocimiento",
  "puissance": "poder", "gloire": "gloria", "honneur": "honor",
  "paix": "paz", "joie": "alegría", "amour": "amor", "haine": "odio",
  "miséricorde": "misericordia", "bonté": "bondad", "vérité": "verdad",
  "mensonge": "mentira", "mort": "muerte", "vie": "vida", "royaume": "reino",
  "œuvre": "obra", "main": "mano", "pied": "pie", "yeux": "ojos",
  "cœur": "corazón", "voix": "voz", "visage": "rostro",
};

// Common adjectives, ordinals, misc words and remaining nouns (port of _EXTRA_WORDS).
const _EXTRA_WORDS = {
  "premier": "primero", "première": "primera", "premiers": "primeros",
  "deuxième": "segundo", "second": "segundo", "seconde": "segunda",
  "troisième": "tercero", "quatrième": "cuarto", "cinquième": "quinto",
  "sixième": "sexto", "septième": "séptimo", "huitième": "octavo",
  "dernier": "último", "dernière": "última", "principal": "principal",
  "principale": "principal", "principales": "principales",
  "vivant": "vivo", "vivante": "viva", "vivants": "vivos",
  "domestique": "doméstico", "domestiques": "domésticos",
  "divers": "diverso", "diverse": "diversa", "diverses": "diversas",
  "vert": "verde", "verte": "verde", "terrestre": "terrestre",
  "terrestres": "terrestres", "ressemblant": "parecido",
  "ressemblante": "parecida", "gros": "grande / gordo",
  "nombreux": "numerosos", "nombreuse": "numerosa",
  "propre": "propio / limpio", "propres": "propios",
  "unique": "único", "chaque": "cada", "même": "mismo / incluso",
  "mêmes": "mismos", "seul": "solo", "seule": "sola", "seulement": "solamente",
  "très": "muy", "aussi": "también / tan", "encore": "todavía / aún",
  "toujours": "siempre", "jamais": "nunca", "souvent": "a menudo",
  "déjà": "ya", "pas": "no", "ne": "no", "plus": "más", "moins": "menos",
  "bien": "bien", "mal": "mal", "parce": "porque",
  "parce que": "porque", "puis": "luego / después", "ensuite": "después",
  "ainsi": "así / de este modo", "alors": "entonces", "donc": "por tanto",
  "enfin": "por fin / finalmente", "bref": "en resumen", "ras": "ras / raso / plano",
  "lieu": "lugar", "lieux": "lugares", "endroit": "lugar / sitio",
  "comme": "como",
  "vraiment": "realmente / de verdad", "cela": "eso / aquello",
  "ça": "eso", "voilà": "he aquí", "voici": "he aquí",
  "deux": "dos", "trois": "tres", "quatre": "cuatro", "cinq": "cinco",
  "lui-même": "él mismo", "elle-même": "ella misma", "eux-mêmes": "ellos mismos",
  "au-dessus": "por encima / arriba", "au-dessous": "por debajo / abajo",
  "au-dedans": "dentro", "au-dehors": "fuera", "dessous": "debajo",
  "dessus": "encima", "autour": "alrededor", "ensemble": "juntos / conjunto",
  "presque": "casi", "autant": "tanto",
  "tant": "tanto", "tellement": "tanto", "cependant": "sin embargo",
  "pourtant": "sin embargo", "néanmoins": "no obstante",
  "d'ailleurs": "por otra parte", "végétation": "vegetación",
  "foule": "multitud / muchedumbre", "journée": "día / jornada",
  "variété": "variedad", "humain": "humano", "humaine": "humana",
  "humains": "humanos", "oiseau": "pájaro / ave", "oiseaux": "pájaros / aves",
  "animal": "animal", "animaux": "animales", "marin": "marino",
  "marins": "marinos", "onde": "ola / agua", "fruitier": "frutal",
  "fruitiers": "frutales", "graine": "semilla", "graines": "semillas",
  "pépin": "pepita", "pépins": "pepitas", "noyau": "hueso / núcleo",
  "noyaux": "huesos / núcleos", "plante": "planta", "plantes": "plantas",
  "herbe": "hierba", "herbes": "hierbas", "branche": "rama",
  "branches": "ramas", "racine": "raíz", "racines": "raíces",
  "feuille": "hoja", "feuilles": "hojas", "trône": "trono",
  "sceptre": "cetro", "couronne": "corona", "chef": "jefe / cabeza",
  "chefs": "jefes", "armée": "ejército", "armées": "ejércitos",
  "soldat": "soldado", "soldats": "soldados", "épée": "espada",
  "bouclier": "escudo", "lance": "lanza", "arc": "arco", "flèche": "flecha",
  "ville": "ciudad", "villes": "ciudades", "village": "aldea",
  "villageois": "aldeanos", "chemin": "camino", "sentier": "sendero",
  "porte": "puerta", "portes": "puertas", "mur": "muro", "murs": "muros",
  "tour": "torre", "chambre": "habitación", "lit": "cama", "table": "mesa",
  "chaise": "silla", "robe": "vestido", "vêtement": "vestido / ropa",
  "vêtements": "ropa", "habit": "traje", "chaussure": "zapato",
  "manteau": "abrazo / capa", "bâton": "bastón",
  "bâtons": "bastones", "pierre": "piedra", "pierres": "piedras",
  "or": "oro", "argent": "plata / dinero", "perle": "perla",
  "joyau": "joya", "trésor": "tesoro", "trésors": "tesoros",
  "don": "regalo / don", "dons": "regalos", "cadeau": "regalo",
  "présent": "regalo / presente", "offrande": "ofrenda",
  "cultivateur": "agricultor", "berger": "pastor", "bergers": "pastores",
  "pêcheur": "pescador / pecador", "pêcheurs": "pescadores",
  "voyage": "viaje", "voyages": "viajes", "voyageur": "viajero",
  "nomade": "nómada", "étranger": "extranjero", "étrangers": "extranjeros",
  "hôte": "huésped", "invité": "invitado", "invités": "invitados",
  "témoin": "testigo", "témoins": "testigos", "missionnaire": "misionero",
  "envoyé": "enviado", "héros": "héroe", "héritier": "heredero",
  "esclave": "esclavo", "esclaves": "esclavos", "pharaon": "faraón",
  "césar": "césar", "gouverneur": "gobernador", "judge": "juez",
  "juge": "juez", "juges": "jueces", "avocat": "abogado",
  "meurtrier": "asesino", "lièvre": "liebre", "tortue": "tortuga",
  "serpent": "serpiente", "serpents": "serpientes", "colombe": "paloma",
  "colombes": "palomas", "corbeau": "cuervo", "aigle": "águila",
  "pigeon": "paloma", "lion": "león", "lions": "leones", "lionne": "leona",
  "ours": "oso", "loup": "lobo", "loups": "lobos", "renard": "zorro",
  "cheval": "caballo", "chevaux": "caballos", "âne": "asno", "ânes": "asnos",
  "brebis": "oveja", "mouton": "oveja / carnero", "moutons": "ovejas",
  "agneau": "cordero", "agneaux": "corderos", "chèvre": "cabra",
  "vache": "vaca", "boeuf": "buey", "bœuf": "buey", "taureau": "toro",
  "chameau": "camello", "chameaux": "camellos", "chacal": "chacal",
  "souris": "ratón", "chat": "gato", "chien": "perro", "chiens": "perros",
  "abeille": "abeja", "fourmi": "hormiga", "mouche": "mosca",
  "sauterelle": "langosta", "sauterelles": "langostas", "criquet": "langosta",
  "ver": "lombriz / gusano", "vers": "alta / gusano", "miel": "miel",
  "lait": "leche", "beurre": "mantequilla", "fromage": "queso",
  "viande": "carne", "sel": "sal", "sucre": "azúcar", "huile": "aceite",
  "vinaigre": "vinagre", "blé": "trigo", "orge": "cebada",
  "raisin": "uva", "raisins": "uvas", "vigne": "vid", "vignes": "vides",
  "figue": "higo", "olive": "aceituna", "oleifère": "oleífero",
  "grenade": "granada", "pomme": "manzana", "pomme de terre": "patata",
  "maison": "casa", "maisons": "casas", "cuisine": "cocina", "jardin": "jardín",
  "champ": "campo",
  "champs": "campos", "vigne": "vid", "raison": "razón",
  "temps": "tiempo", "moment": "momento", "instant": "instante",
  "heure": "hora", "heures": "horas", "minute": "minuto", "seconde": "segundo",
  "semaine": "semana", "semaines": "semanas", "mois": "mes", "saison": "estación",
  "printemps": "primavera", "été": "verano", "automne": "otoño",
  "hiver": "invierno", "matin": "mañana", "matins": "mañanas",
  "soir": "tarde / noche", "soirée": "tarde / velada", "nuit": "noche",
  "nuits": "noches", "aube": "alba", "crépuscule": "crepúsculo",
  "minuit": "medianoche", "midi": "mediodía", "zéro": "cero",
  "un": "uno", "deux": "dos", "trois": "tres", "quatre": "cuatro",
  "cinq": "cinco", "six": "seis", "sept": "siete", "huit": "ocho",
  "neuf": "nueve", "dix": "diez", "cent": "cien", "mille": "mil",
  "quoi": "qué", "pourquoi": "por qué", "combien": "cuánto",
  "comment": "cómo", "où": "dónde / donde", "quand": "cuándo / cuando",
  "qui": "quién / que", "que": "qué / que", "quel": "cuál / qué",
  "quelle": "cuál / qué", "celui": "ese / aquel", "celle": "esa / aquella",
  "ceux": "esos / aquellos", "celles": "esas / aquellas",
  "quelqu'un": "alguien", "quelque chose": "algo", "quelque": "algún",
  "quelques": "unos / algunos", "personne": "persona / nadie",
  "rien": "nada", "tout monde": "todo el mundo", "toute": "toda",
  "leçon": "lección", "exemple": "ejemplo", "exemples": "ejemplos",
  "grâce": "gracia", "grâces": "gracias", "faute": "falta / culpa",
  "fautes": "faltas", "voiture": "coche", "route": "ruta / camino",
  "routes": "rutas", "pont": "puente", "ponts": "puentes",
  "château": "castillo", "châteaux": "castillos", "palais": "palacio",
  "maison de Dieu": "casa de Dios", "tournoi": "torneo",
};

// High-frequency vocabulary surfaced by the missing-word analysis of the Bible
// text (mostly common nouns, adjectives, adverbs and function words).
const _BIBLE_WORDS = {
  "devant": "delante / frente a", "vos": "vuestro", "eux": "ellos",
  "effet": "efecto (en effet = de hecho)", "ni": "ni", "monde": "mundo",
  "maintenant": "ahora", "part": "parte", "cet": "este", "afin": "para (afin de)",
  "ans": "años", "parmi": "entre / en medio de", "non": "no",
  "près": "cerca (de)", "aucun": "ninguno", "aucune": "ninguna",
  "fois": "vez / veces", "côté": "lado", "place": "lugar / sitio",
  "région": "región", "Eh": "¡eh! / ¡oye!", "Oui": "sí",
  "malheur": "desgracia / mal", "Lorsque": "cuando", "fin": "fin",
  "auprès": "junto a / cerca de", "beaucoup": "mucho", "ici": "aquí",
  "juste": "justo", "loin": "lejos", "peu": "poco", "camp": "campamento",
  "également": "también / igualmente", "présence": "presencia",
  "jeune": "joven", "garde": "guardia", "milieu": "medio",
  "envers": "hacia / para con", "vrai": "verdadero", "règne": "reinado / reino",
  "clan": "clan", "clans": "clanes", "face": "cara / rostro",
  "demeure": "morada / casa", "manière": "manera / forma",
  "secours": "socorro / ayuda", "anciens": "ancianos", "faveur": "favor",
  "conduite": "conducta", "travail": "trabajo", "ordres": "órdenes",
  "ordonné": "ordenado", "promis": "prometido", "tribus": "tribus",
  "longtemps": "mucho tiempo", "douze": "doce", "demande": "pedido / solicitud",
  "partie": "parte / partido", "façon": "manera / forma", "fidèles": "fieles",
  "fidèle": "fiel", "mont": "monte", "trop": "demasiado", "cour": "corte / patio",
  "sorte": "tipo / clase", "sortes": "tipos / clases", "tandis": "mientras",
  "bord": "borde / orilla", "choisi": "elegido", "plein": "lleno",
  "sabbat": "sábado", "passé": "pasado", "bout": "extremo / cabo",
  "mari": "esposo / marido", "écrit": "escrito", "règles": "reglas",
  "pitié": "piedad / compasión", "impur": "impuro", "actions": "acciones",
  "cour": "corte / patio", "coups": "golpes", "lendemain": "día siguiente",
  "méchants": "malvados", "coupable": "culpable", "consacré": "consagrado",
  "ceci": "esto", "contraire": "contrario", "ordre": "orden",
  "faux": "falso", "royal": "real", "justes": "justos", "telle": "tal",
  "volonté": "voluntad", "communion": "comunión", "bras": "brazos",
  "plutôt": "más bien", "pur": "puro", "signe": "señal",
  "détresse": "angustia / tribulación", "mesures": "medidas", "fond": "fondo",
  "lois": "leyes", "quarante": "cuarenta", "sens": "sentido",
  "communauté": "comunidad", "pauvres": "pobres", "mauvaise": "mala",
  "adversaires": "adversarios / enemigos", "recueil": "recopilación",
  "poussière": "polvo", "valeur": "valor", "lin": "lino", "complets": "completos",
  "direction": "dirección", "soin": "cuidado", "pleine": "llena",
  "point": "punto", "victoire": "victoria", "hors": "fuera de",
  "kilos": "kilos", "debout": "de pie", "mieux": "mejor",
  "conformément": "conforme a", "messagers": "mensajeros", "aide": "ayuda",
  "cas": "caso", "parents": "padres / parientes", "frontière": "frontera",
  "trente": "treinta", "époque": "época (à l'époque = en esa época)",
  "heureux": "feliz", "coup": "golpe", "Écriture": "Escritura",
  "proche": "cerca / próximo", "sage": "sabio", "derrière": "detrás",
  "regard": "mirada", "autorité": "autoridad", "pauvre": "pobre",
  "fidélité": "fidelidad", "cieux": "cielos", "bétail": "ganado",
  "torrent": "torrente", "Majesté": "Majestad", "entier": "entero",
  "colonnes": "columnas", "intérieur": "interior", "levain": "levadura",
  "piège": "trampa", "semblable": "semejante", "suivant": "siguiente",
  "égard": "consideración (à l'égard = hacia)", "possession": "posesión",
  "travaux": "trabajos", "soumis": "sometido", "croyants": "creyentes",
  "montagneuse": "montañosa", "assez": "bastante", "oui": "sí",
  "durant": "durante", "repos": "descanso", "groupe": "grupo",
  "certains": "algunos", "réponse": "respuesta", "refuge": "refugio",
  "éternelle": "eterna", "compatriotes": "compatriotas", "moitié": "mitad",
  "rêve": "sueño", "tort": "culpa / error (avoir tort = tener culpa)",
  "sages": "sabios", "malade": "enfermo", "moyen": "medio",
  "tué": "matado / muerto", "riche": "rico", "bélier": "carnero",
  "appartient": "pertenece", "Aussitôt": "inmediatamente",
  "aussitôt": "inmediatamente", "responsable": "responsable",
  "tard": "tarde / más tarde",
  "colère": "ira / enojo",
  "descendant": "descendiente", "descendants": "descendientes",
  "habitant": "habitante", "habitants": "habitantes",
  "ancêtre": "antepasado", "ancêtres": "antepasados",
  "ennemis": "enemigos", "cris": "gritos",
  "puisque": "ya que / puesto que", "lorsque": "cuando",
  "quant": "en cuanto a",
  "jeunes": "jóvenes", "désigne": "designa",
  "grange": "granero", "grenier": "granero", "bergerie": "redil",
  "paysans": "campesinos", "fossé": "zanja / foso", "muraille": "muralia",
  "châtiment": "castigo", "récompense": "recompensa", "supplication": "súplica",
  "gémissements": "gemidos", "lamentation": "lamentación", "deuil": "duelo / luto",
  "tribut": "tributo", "impôt": "impuesto", "censure": "censura",
  "interdiction": "prohibición", "déluge": "diluvio", "sécheresse": "sequía",
  "famine": "hambruna", "peste": "peste", "épidémie": "epidemia",
  "abondance": "abundancia", "pénurie": "escasez", "excédent": "excedente",
  "revenus": "ingresos", "richesses": "riquezas", "biens": "bienes",
  "héritage": "herencia", "patrimoine": "patrimonio", "propriété": "propiedad",
  "troupeaux": "rebaños", "bercail": "redil", "étable": "establo",
  "écurie": "establo / cuadra", "pressoir": "lagar", "meule": "piedra de molino",
  "moisson": "cosecha", "récolte": "cosecha", "gerbe": "gavilla",
  "fourrage": "forraje", "foin": "heno", "chaume": "rastrojo",
  "arable": "arable / cultivable", "labour": "barbecho / labranza",
  "brisées": "roturas / restos", "débris": "escombros", "ruines": "ruinas",
  "décombres": "escombros", "cendres": "cenizas", "braises": "brasas",
  "flammes": "llamas", "étincelles": "chispas", "pétrole": "petróleo",
  "charbon": "carbón", "bois": "madera / leña", "branche": "rama",
  "brindille": "ramita", "rameau": "ramo / retoño", "rejeton": "retoño",
  "pousse": "brote", "germe": "germen", "semis": "siembra",
  "pépinière": "vivero / semillero", "verger": "huerto de frutales",
  "pasture": "pastizal / pasto", "pâturage": "pasto / pastizal",
  "lande": "páramo / brezal", "bruyère": "brezo", "buisson": "arbusto",
  "fourré": "matorral", "bosquet": "bosquecillo", "taillis": "matorral",
  "forestière": "forestal", "défrichée": "desbrozada / roturada",
  "métayage": "aparcería", "fermage": "arrendamiento",
  "redevance": "tributo / canon", "cens": "censo / canon",
  "coutume": "costumbre", "tradition": "tradición", "mœurs": "costumbres",
  "cultes": "cultos", "rite": "rito", "cérémonie": "ceremonia",
  "pèlerinage": "peregrinación", "pèlerins": "peregrinos", "exode": "éxodo",
  "captivité": "cautiverio", "servage": "servidumbre", "corvée": "presta / faena",
  "dîme": "diezmo", "prémices": "primicias", "offrandes": "ofrendas",
  "holocauste": "holocausto", "encens": "incienso", "cendre": "ceniza",
  "calice": "cáliz", "coupe": "copa / cáliz", "patène": "patena",
  "ostensoir": "ostensorio", "encensoir": "incensario", "goupillon": "hisopo",
  "auge": "pesebre", "crèche": "pesebre", "mangeoire": "pesebre / comedero",
  "fenil": "henil", "silo": "silo", "cellier": "bodega",
  "cave": "bodega / sótano", "pavillon": "pabellón",
  "tente": "tienda de campaña", "abri": "refugio / cobijo", "hutte": "choza / cabaña",
  "cabane": "chabola / cabaña", "paillote": "chabola / cabaña",
  "abreuvoir": "abrevadero", "citernes": "cisternas", "puits": "pozo",
  "fontaine": "fuente (de agua)", "ruisseau": "arroyo", "ravin": "barranco",
  "gorge": "garganta / desfiladero", "vallées": "valles", "crête": "cumbre / cima",
  "sommet": "cima / cumbre", "plateau": "meseta", "plaine": "llanura",
  "champs cultivés": "campos cultivados",
  "dix-sept": "diecisiete", "dix-huit": "dieciocho",
  "dix-neuf": "diecinueve", "vingt et un": "veintiuno",
  "vingt-deux": "veintidós", "trente-sept": "treinta y siete",
  "quarante-deux": "cuarenta y dos",
  "cinquante-trois": "cincuenta y tres",
  "soixante-dix": "setenta", "soixante-dix-huit": "setenta y ocho",
  "quatre-vingts": "ochenta", "quatre-vingt-dix": "noventa",
  "million": "millón", "millions": "millones",
  "millier": "millar", "milliers": "miles",
  "cent quarante": "ciento cuarenta",
  "cent cinquante": "ciento cincuenta",
  "cent soixante": "ciento sesenta",
  "deux cents": "doscientos",
  "trois cents": "trescientos",
  "cinq cents": "quinientos",
  "mille": "mil",
  "mille deux cents": "mil doscientos",
  "deux mille": "dos mil",
  "trois mille": "tres mil",
  "quatre mille": "cuatro mil",
  "cinq mille": "cinco mil",
  "dix mille": "diez mil",
  "six mille": "seis mil",
  "sept mille": "siete mil",
  "huit mille": "ocho mil",
  "neuf mille": "nueve mil",
  "douze mille": "doce mil",
  "quinze mille": "quince mil",
  "vingt mille": "veinte mil",
  "trente mille": "treinta mil",
  "cinquante mille": "cincuenta mil",
  "cent mille": "cien mil",
  "sept cent": "setecientos",
  "quarante et un": "cuarenta y uno",
  "cinquante et un": "cincuenta y uno",
  "soixante et un": "sesenta y uno",
  "soixante-cinq": "sesenta y cinco",
  "vingt-cinq": "veinticinco",
  "trente-deux": "treinta y dos",
  "trente-trois": "treinta y tres",
  "treize": "trece", "quatorze": "catorce",
  "quinze": "quince", "seize": "dieciséis",
  "onze": "once", "vingt": "veinte", "cent": "cien",
  "vingt-quatre": "veinticuatro",
  "vingt-six": "veintiséis",
  "trente-et-un": "treinta y uno",
  "trente et un": "treinta y uno",
  "quarante-cinq": "cuarenta y cinco",
  "quarante-huit": "cuarenta y ocho",
  "cinquante-deux": "cincuenta y dos",
  "cinquante-neuf": "cincuenta y nueve",
  "soixante-trois": "sesenta y tres",
  "soixante-huit": "sesenta y ocho",
  "soixante-douze": "setenta y dos",
  "quatre-vingt-deux": "ochenta y dos",
  "quatre-vingt-treize": "noventa y tres",
  "cent deux": "ciento dos",
  "cent trois": "ciento tres",
  "cent dix": "ciento diez",
  "cent vingt": "ciento veinte",
  "cent trente": "ciento treinta",
"cent quarante-cinq": "ciento cuarenta y cinco",
  "cent cinquante-trois": "ciento cincuenta y tres",
  "deux cent": "doscientos",
  "rois": "reyes", "lévites": "levitas", "lévite": "levita",
  "aujourd'hui": "hoy / el día de hoy",
  "prière": "oración", "prières": "oraciones",
  "tel": "tal", "tels": "tales", "telle": "tal", "telles": "tales",
  "troupes": "tropas", "troupe": "tropa",
  "long": "largo", "longue": "larga", "longues": "largas",
  "complètement": "completamente", "partout": "por todas partes",
  "tombeau": "tumba / sepulcro", "tombes": "tumbas",
  "complet": "completo", "complète": "completa", "complets": "completos",
  "complètes": "completas", "entière": "entera / completa", "entier": "entero",
  "rituel": "ritual", "localités": "localidades", "localité": "localidad",
  "morceaux": "pedazos / trozos", "morceau": "pedazo / trozo",
  "laquelle": "la cual / que", "lequel": "el cual / que", "lesquels": "los cuales",
  "royale": "real (real, de rey)", "royal": "real", "royales": "reales",
  "prisonniers": "prisioneros", "prisonnier": "prisionero",
  "témoignage": "testimonio", "témoignages": "testimonios",
  "prêt": "listo / prestado", "prête": "lista / prestada", "prêts": "listos",
  "Pâque": "Pascua", "dehors": "fuera / afuera",
  "rempli": "lleno / repleto", "remplie": "llena", "remplis": "llenos",
  "travers": "través (à travers = a través)",
  "assis": "sentado", "assise": "sentada",
  "affaire": "asunto / negocio", "affaires": "asuntos",
  "défaut": "defecto / falta", "vieux": "viejo", "vieille": "vieja",
  "appel": "llamado / llamamiento", "geste": "gesto",
  "glorieuse": "gloriosa", "glorieux": "glorioso",
  "abominables": "abominables", "abominable": "abominable",
  "butin": "botín / presa", "certain": "cierto / cierto hombre",
  "certains": "algunos", "quiconque": "quienquiera / cualquiera que",
  "liste": "lista", "listes": "listas",
  "particulier": "particular", "particulière": "particular",
  "détruit": "destruido", "détruite": "destruida",
  "sécurité": "seguridad", "forte": "fuerte", "fortes": "fuertes",
  "vite": "rápido / de prisa", "sacrée": "sagrada",
  "veuve": "viuda", "veuf": "viudo", "autrefois": "antes / antiguamente",
  "ailes": "alas", "aile": "ala",
  "digne": "digno", "digne de": "digno de", "grandeur": "grandeza",
  "assemblée": "asamblea", "assemblées": "asambleas",
  "belle": "bella / hermosa", "beau": "bello / hermoso",
  "propos": "palabras / asunto (à propos = a propósito)",
  "pièce": "pieza/ habitación", "pièces": "piezas",
  "désirs": "deseos", "désir": "deseo",
  "méchant": "malvado", "méchante": "malvada",
  "fleuve": "río / corriente", "fleuves": "ríos",
  "faite": "hecha", "faits": "hechos",
  "propriétaire": "dueño / propietario",
  "haute": "alta", "hautes": "altas",
  "suivantes": "siguientes", "suivante": "siguiente",
  "païens": "paganos", "païen": "pagano",
  "événements": "acontecimientos", "événement": "acontecimiento",
  "épouse": "esposa", "époux": "esposo", "épouses": "esposas",
  "décision": "decisión", "décisions": "decisiones",
  "chérubins": "querubines", "chérubin": "querubín",
  "contenu": "contenido", "bientôt": "pronto",
  "bénédiction": "bendición", "bénédictions": "bendiciones",
  "mépris": "desprecio", "puissant": "poderoso",
  "puissante": "poderosa", "retour": "regreso / vuelta",
  "état": "estado", "Psaume": "Salmo", "psaume": "salmo",
  "capable": "capaz", "gauche": "izquierda",
  "répertoire": "repertorio", "dixième": "décimo",
  "cinquante": "cincuenta", "soixante": "sesenta",
  "présentation": "presentación",
  "d'abord": "primero / en primer lugar", "d'abord que": "antes de que",
  "mets": "platos / manjares", "mètre": "metro", "mètres": "metros",
  "lettre": "carta / letra", "lettres": "cartas / letras",
  "actes": "hechos / actos", "acte": "acto",
  "terreur": "terror / espanto", "terriblement": "terriblemente",
  "environ": "aproximadamente / unos",
  "fuite": "huida / fuga", "fuites": "huidas",
  "fureur": "furor / furia", "conseil": "consejo / plan",
  "conseils": "consejos", "chair": "carne", "ventre": "vientre",
  "génération": "generación", "générations": "generaciones",
  "prochain": "prójimo / próximo", "prochaine": "próxima",
  "porche": "pórtico", "porches": "pórticos",
  "question": "pregunta / cuestión", "questions": "preguntas",
  "malédiction": "maldición", "malédictions": "maldiciones",
  "profondément": "profundamente", "malheureux": "desdichado / infeliz",
  "malheureuse": "desdichada", "nécessaire": "necesario",
  "cèdre": "cedro", "cèdres": "cedros",
  "plusieurs": "varios / varios", "taille": "talla / estatura",
  "sot": "necio / tonto", "sotte": "necia / tonta",
  "cheveux": "cabellos / pelo", "faible": "débil", "faibles": "débiles",
  "fortifiées": "fortificadas", "fortifié": "fortificado",
  "Sauveur": "Salvador", "sauveur": "salvador",
  "tas": "montón / pila", "terrible": "terrible",
  "convaincus": "convencidos", "grave": "grave",
  "conséquences": "consecuencias", "conséquence": "consecuencia",
  "accord": "acuerdo / trato", "accords": "acuerdos",
  "supérieur": "superior", "supérieure": "superior",
  "demi": "medio", "demie": "media",
  "barque": "barca", "barques": "barcas",
  "grains": "granos", "grain": "grano",
  "prodiges": "prodigios / portentos", "prodige": "prodigio",
  "demain": "mañana (día siguiente)",
  "crime": "crimen", "crimes": "crímenes",
  "distance": "distancia", "bandes": "bandas / grupos",
  "largeur": "anchura / ancho", "entièrement": "enteramente",
  "intermédiaire": "intermediario / intermedio",
  "âge": "edad", "âges": "edades",
  "épreuve": "prueba / aflicción", "épreuves": "pruebas",
  "quantité": "cantidad", "désastre": "desastre",
  "Ah": "¡ah! / ¡oh!", "Pause": "pausa / selah", "pause": "pausa",
  "bienveillance": "benevolencia / bondad",
  "termes": "términos / condiciones", "terme": "término",
  "prostituée": "prostituta", "prostituées": "prostitutas",
  "Toutefois": "no obstante / sin embargo", "toutefois": "no obstante",
  "an": "año", "réalité": "realidad", "misère": "miseria",
  "royauté": "realeza / reino", "n'importe": "no importa (n'importe quoi = cualquier cosa)",
  "large": "ancho / amplio", "larges": "anchos",
  "meurtre": "homicidio / asesinato", "proie": "presa",
  "chacune": "cada una", "servantes": "sirvientas / siervas", "servante": "sirvienta",
  "reproches": "reproches", "reproche": "reproche / reprobación",
  "fermement": "firmemente", "précieux": "precioso / valioso",
  "précieuse": "preciosa", "aveugles": "ciegos", "aveugle": "ciego",
  "odorante": "olorosa", "méchanceté": "maldad",
  "immense": "immensa / enorme", "purification": "purificación",
  "début": "comienzo / principio", "entourage": "entorno / séquito",
  "garçon": "muchacho / niño", "garçons": "muchachos",
  "rebelles": "rebeldes", "rebelde": "rebelde",
  "fondations": "cimientos / fundamentos", "fondation": "fundación",
  "Cité": "ciudad", "cité": "ciudad",
  "enceinte": "embarazada / dentro de los muros",
  "malgré": "a pesar de", "perte": "pérdida",
  "voisines": "vecinas", "voisine": "vecina",
  "bouc": "macho cabrío / chivo", "personnel": "personal",
  "forteresse": "fortaleza", "siens": "los suyos",
  "sien": "suyo", "agréable": "agradable",
  "total": "total", "rang": "rango / fila",
  "fonctionnaires": "funcionarios", "liberté": "libertad",
  "innocent": "inocente", "innocente": "inocente", "innocents": "inocentes",
  "socles": "bases / peanas", "socle": "base",
  "avenir": "futuro / porvenir", "outre": "además / allende (en outre = además)",
  "étrangères": "extranjeras", "étrangère": "extranjera",
  "grasses": "grasas", "grasse": "grasa",
  "preuve": "prueba / evidencia", "preuves": "pruebas",
  "ceinture": "cinturón / faja", "rapport": "informe / relación",
  "vestibule": "vestíbulo / atrio", "certainement": "ciertamente",
  "discours": "discurso / discursos", "proclamations": "proclamaciones",
  "possible": "posible", "dents": "dientes", "dent": "diente",
  "bienfaits": "beneficios", "bienfait": "beneficio",
  "libre": "libre", "libres": "libres",
  "sec": "seco", "sèche": "seca", "sèches": "secas",
  "hauteurs": "alturas", "hauteur": "altura",
  "position": "posición", "pareil": "parecido / semejante",
  "pareille": "parecida", "attentif": "atento",
  "pure": "pura", "pures": "puras",
  "cri": "grito", "cris": "gritos",
  "tranquille": "tranquilo", "tranquilles": "tranquilos",
  "compagnie": "compañía", "genre": "género / clase",
  "occasion": "ocasión", "véritable": "verdadera / auténtica",
  "véritablement": "verdaderamente",
  "lèvres": "labios", "lèvre": "labio",
  "indignation": "indignación", "profit": "provecho / beneficio",
  "titre": "título", "lèpre": "lepra",
  "barres": "barras", "barre": "barra",
  "domaine": "dominio / campo", "domaines": "dominios",
  "menaces": "amenazas", "menace": "amenaza",
  "messager": "mensajero", "messagers": "mensajeros",
  "jusque": "hasta", "jusqu'à": "hasta",
  "vraie": "verdadera", "vraies": "verdaderas",
  "rosée": "rocío", "intentions": "intenciones", "intention": "intención",
  "exactement": "exactamente", "rouleau": "rollo / pergamino",
  "tendre": "tender / tierno",
  "vœu": "voto / promesa / deseo", "joyeux": "alegre", "joyeuse": "alegre",
  "défaite": "derrota", "brisé": "roto / quebrado", "brisée": "rota",
  "commun": "común", "commune": "común",
  "loyauté": "lealtad", "protecteur": "protector",
  "impossible": "imposible", "terrain": "terreno",
  "somme": "suma / cantidad", "conséquent": "consecuente",
  "davantage": "más / aún más", "fléau": "plaga / flagelo",
  "règle": "regla", "règles": "reglas",
  "colonne": "columna", "colonnes": "columnas",
  "merveilles": "maravillas", "merveille": "maravilla",
  "impure": "impura", "élevé": "elevado", "élevée": "elevada",
  "courageux": "valiente / valeroso", "courageuses": "valientes",
  "beauté": "belleza", "unis": "unidos",
  "soudain": "de repente / súbito", "ailleurs": "en otro lugar / en otra parte",
  "renommée": "renombre / fama", "révolte": "revuelta / rebelión",
  "fidèlement": "fielmente", "violette": "violeta",
  "simple": "simple", "simples": "simples",
  "dure": "dura", "durs": "duros",
  "succès": "éxito", "appui": "apoyo",
  "vaillants": "valientes", "déportation": "deportación", "tempête": "tormenta",
  "avertissements": "advertencias", "avertissement": "advertencia",
  "sauf": "excepto / salvo", "période": "período",
  "intelligent": "inteligente", "vigueur": "vigor",
  "procès": "juicio / proceso", "siècle": "siglo",
  "désormais": "de ahora en adelante", "figuier": "higuera",
  "responsabilité": "responsabilidad", "clairement": "claramente",
  "grêle": "granizo", "malfaiteurs": "malhechores",
  "notables": "notables / prominentes", "centimètres": "centímetros",
  "rompu": "roto / quebrado", "fardeau": "carga / peso",
  "uniquement": "únicamente", "parfaitement": "perfectamente",
  "tiers": "tercio / tercero", "secrétaire": "secretario / escriba",
  "splendeur": "esplendor", "fierté": "orgullo",
  "miraculeux": "milagroso", "irréprochable": "irreprochable",
  "gras": "gordo / graso", "grosse": "gorda",
  "interdit": "prohibido", "interdite": "prohibida",
  "œil": "ojo", "soigneusement": "cuidadosamente",
  "provenant": "procedente de", "réputation": "reputación / fama",
  "courant": "actual / corriente", "signification": "significado",
  "profond": "profundo", "profonde": "profunda",
  "incapable": "incapaz", "tôt": "temprano",
  "cachette": "escondite", "difficile": "difícil",
  "ardente": "ardiente", "défense": "defensa",
  "clair": "claro", "claire": "clara",
  "voleur": "ladrón", "voleurs": "ladrones",
  "artisans": "artesanos", "artisan": "artesano",
  "attribué": "atribuido", "intérieure": "interior",
  "ossements": "huesos", "orientale": "oriental",
  "orgueilleux": "orgulloso", "attachés": "atados / unidos",
  "lointaines": "lejanas", "convaincu": "convencido",
  "sévèrement": "severamente", "éternel": "eterno",
  "parent": "pariente", "parents": "padres / parientes",
  "plat": "plato / llano", "dur": "duro",
  "privé": "privado", "incapables": "incapaces",
  "violent": "violento", "honnête": "honesto / honrada",
  "solide": "sólido", "cramoisie": "carmesí",
  "action": "acción", "moindre": "menor",
  "passant": "transeúnte / caminante",
  "général": "general", "revanche": "revancha / desquite",
  "juif": "judío", "juive": "judía", "juifs": "judíos",
  "romain": "romano", "romaine": "romana",
  "dispersés": "dispersos", "dispersées": "dispersas",
  "circoncis": "circunciso / circuncidado",
  "dirigeants": "dirigentes", "dirigeant": "dirigente / líder",
  "maudit": "maldito", "maudite": "maldita",
  "déportés": "deportados", "déporté": "deportado",
  "solennellement": "solemnemente", "sainte": "santa",
  "saints": "santos", "auparavant": "anteriormente / antes",
  "infidèles": "infieles", "infidèle": "infiel",
  "meilleur": "mejor", "meilleurs": "mejores",
  "complainte": "lamento / lamentación", "redoutable": "temible",
  "attribuée": "atribuida", "irrité": "irritado / enojado",
  "irritée": "irritada", "reconnaissance": "reconocimiento / gratitud",
  "auquel": "al cual / al que", "auxquels": "a los cuales",
  "important": "importante", "importante": "importante",
  "ligne": "línea", "lignes": "líneas",
  "épis": "espigas", "épi": "espiga",
  "écart": "separación / lugar apartado",
  "éfod": "efod",
  "épaules": "hombros", "épaule": "hombro",
  "extérieur": "exterior / afuera", "extérieure": "exterior",
  "cuve": "cuba / tinaja", "cuves": "cubas",
};

// Proper names (people and places) -> Spanish renderings.
const _BIBLE_NAMES = {
  "Israël": "Israel", "Israélite": "israelita", "Israélites": "israelitas",
  "Jérusalem": "Jerusalén", "Moïse": "Moisés", "Juda": "Judá",
  "Jacob": "Jacob", "Saül": "Saúl", "Joseph": "José", "Aaron": "Aarón",
  "Josué": "Josué", "Jérémie": "Jeremías", "Abraham": "Abraham",
  "Égypte": "Egipto", "Galaad": "Galaad", "Moab": "Moab",
  "Manassé": "Manasés", "Joab": "Joab", "Jean": "Juan",
  "Benjamin": "Benjamín", "Jéroboam": "Jeroboam", "Ézékias": "Ezequías",
  "Nabucodonosor": "Nabucodonosor", "Jonatan": "Jonatán", "Lévi": "Leví",
  "Élisée": "Eliseo", "Élie": "Elías", "Ruben": "Rubén", "Gad": "Gad",
  "Simon": "Simón", "Job": "Job", "Baal": "Baal", "Galilée": "Galilea",
  "Amorites": "amorreos", "Égyptiens": "egipcios", "Paul": "Pablo",
  "Éfraïm": "Efraín", "Josias": "Josías", "Amos": "Amós", "Osée": "Oseas",
  "Joël": "Joel", "Abdias": "Abdías", "Jonas": "Jonás", "Michée": "Miqueas",
  "Nahum": "Nahúm", "Habacuc": "Habacuc", "Sophonie": "Sofonías",
  "Aggée": "Ageo", "Zacharie": "Zacarías", "Malachie": "Malaquías",
  "David": "David", "Salomon": "Salomón", "Samuel": "Samuel",
  "Natan": "Natán", "Daniel": "Daniel", "Ézéchiel": "Ezequiel",
  "Pierre": "Pedro", "Marie": "María", "Judas": "Judas",
  "Philippe": "Felipe", "André": "Andrés", "Jacques": "Santiago",
  "Matthieu": "Mateo", "Marc": "Marcos", "Luc": "Lucas",
  "Hérode": "Herodes", "Pilate": "Pilato", "Judée": "Judea",
  "Israël": "Israel", "Judéens": "judeos", "Babylone": "Babilonia",
  "Babyloniens": "babilonios", "Assyrie": "Asiria", "Assyriens": "asirios",
  "Perse": "Persia", "Perses": "persas", "Cyrus": "Ciro",
  "Darius": "Darío", "Nabuchodonosor": "Nabucodonosor",
  "Édom": "Edom", "Édomites": "edomitas", "Moabites": "moabitas",
  "Ammon": "Amón", "Ammonites": "amonitas", "Philistins": "filisteos",
  "Cananéens": "cananeos", "Canaan": "Canaán", "Hébreux": "hebreos",
  "Araméens": "arameos", "Syriens": "sirios", "Syrie": "Siria",
  "Phénicie": "Fenicia", "Tyr": "Tiro", "Sidon": "Sidón",
  "Ninive": "Nínive", "Ninive": "Nínive", "Bethléem": "Belén",
  "Nazareth": "Nazaret", "Capharnaüm": "Cafarnaúm", "Jourdain": "Jordán",
  "mont Sinaï": "monte Sinaí", "Sion": "Sión", "Golgotha": "Gólgota",
  "Égée": "Egeo",
  "Jéricho": "Jericó", "Jéhu": "Jehú", "Sédécias": "Sedequías",
  "Balaam": "Balaam", "Élazar": "Eleazar", "Gédéon": "Gedeón",
  "Dan": "Dan", "Achab": "Acab", "Bachan": "Basán", "Yoyada": "Joyadá",
  "Ésaïe": "Isaías", "Abimélek": "Abimelec", "Ésaü": "Esaú",
  "Siméon": "Simeón", "Hébron": "Hebrón", "Joram": "Joram",
  "Mardochée": "Mardoqueo", "Noé": "Noé", "Neftali": "Neftalí",
  "Sadoc": "Sadoc", "Abram": "Abram", "Roboam": "Roboam",
  "Guibéa": "Gibea", "Haman": "Amán", "Dagon": "Dagón",
  "Amon": "Amón", "Elisée": "Eliseo", "Élisée": "Eliseo",
  "Goliath": "Goliat", "Absalom": "Absalón", "Ézéchias": "Ezequías",
  "Manassé": "Manasés", "Josias": "Josías", "Josaphat": "Josafat",
  "Jehoram": "Joram", "Ozias": "Ozías", "Achaz": "Acaz",
  "éphraïmites": "efraimitas", "Éphraïm": "Efraín",
  "Beth-Shemesh": "Bet-semes", "Guibéa": "Gibea", "Garo": "Garo",
  "Marécha": "Maresa", "Lakich": "Laquis", "Aïalon": "Ajalón",
  "Penouël": "Peniel", "Tirtsa": "Tirsa", "Gabaon": "Gabaón",
  "Horma": "Horma", "Haïl": "Hail",
  "Caleb": "Caleb", "Abner": "Abner", "Yéchoua": "Josué",
  "Jizréel": "Jezreel", "Jessé": "Jesé", "Coré": "Coré",
  "Benaya": "Benaía", "Joaquim": "Joaquín", "Balac": "Balac",
  "Chemaya": "Semaías", "Amalécites": "amalecitas", "Guilgal": "Gilgal",
  "Mispa": "Mizpa", "Chiméi": "Simei", "Sinaï": "Sinaí",
  "Booz": "Booz", "Mika": "Mica", "Azaria": "Azarías",
  "Asa": "Asá", "Amassia": "Amasías",
  "Esther": "Ester", "Barnabas": "Bernabé", "Quéhath": "Cohat",
  "Sihon": "Sehón", "Merari": "Merari", "Hèchebon": "Hesbón",
  "Madianites": "madianitas", "Yohanan": "Johanán",
  "Benjaminites": "benjaminitas", "Yotam": "Jotam", "Ruth": "Rut",
  "Hilquia": "Hilcías", "Guedalia": "Guedalías",
  "Jébusites": "jebuseos", "Ismaël": "Ismael", "Yonatan": "Jonatán",
  "Ahaz": "Acaz", "Asser": "Aser", "Méditerranée": "Mar Mediterráneo",
  "Tamar": "Tamar", "Issakar": "Isacar", "Assaf": "Asaf",
  "Ben-Hadad": "Ben-adad", "Noémi": "Noemí", "Hiram": "Hiram",
  "Ahazia": "Ocozías", "Hanania": "Ananías", "Séir": "Seir",
  "Challoum": "Salum", "Timothée": "Timoteo", "Maaka": "Maaca",
  "Ramoth": "Ramot", "Supposons": "supongamos", "Alléluia": "Aleluya",
};

// ---- grammar: irregular verbs -> (infinitive, tense) ----------------------
const _VERB_IRREGULAR = {
  "est": ["être", "présent 3sg"], "sont": ["être", "présent 3pl"],
  "suis": ["être", "présent 1sg"], "es": ["être", "présent 2sg"],
  "êtes": ["être", "présent 2pl"], "étais": ["être", "imparfait 1/2sg"],
  "était": ["être", "imparfait 3sg"], "étaient": ["être", "imparfait 3pl"],
  "sera": ["être", "futur 3sg"], "fut": ["être", "passé simple 3sg"],
  "soit": ["être", "subjonctif 3sg"],
  "soient": ["être", "subjonctif 3pl"], "soyons": ["être", "impératif 1pl"],
  "soyez": ["être", "impératif 2pl"],
  "a": ["avoir", "présent 3sg"], "ont": ["avoir", "présent 3pl"],
  "ai": ["avoir", "présent 1sg"], "as": ["avoir", "présent 2sg"],
  "avait": ["avoir", "imparfait 3sg"], "avaient": ["avoir", "imparfait 3pl"],
  "aura": ["avoir", "futur 3sg"], "eut": ["avoir", "passé simple 3sg"],
  "ait": ["avoir", "subjonctif 3sg"], "aient": ["avoir", "subjonctif 3pl"],
  "fit": ["faire", "passé simple 3sg"], "faisait": ["faire", "imparfait 3sg"],
  "faisons": ["faire", "présent 1pl"], "faites": ["faire", "présent 2pl"],
  "fera": ["faire", "futur 3sg"], "fasse": ["faire", "subjonctif 3sg"],
  "faisant": ["faire", "participe présent"],
  "alla": ["aller", "passé simple 3sg"], "allait": ["aller", "imparfait 3sg"],
  "ira": ["aller", "futur 3sg"], "vont": ["aller", "présent 3pl"],
  "vint": ["venir", "passé simple 3sg"], "viendra": ["venir", "futur 3sg"],
  "vient": ["venir", "présent 3sg"], "venait": ["venir", "imparfait 3sg"],
  "venez": ["venir", "présent 2pl"], "devenez": ["devenir", "présent 2pl"],
  "devint": ["devenir", "passé simple 3sg"], "deviendra": ["devenir", "futur 3sg"],
  "revint": ["revenir", "passé simple 3sg"],
  "dit": ["dire", "passé simple 3sg"], "disait": ["dire", "imparfait 3sg"],
  "dira": ["dire", "futur 3sg"], "disant": ["dire", "participe présent"],
  "disent": ["dire", "présent 3pl"], "dis": ["dire", "présent 1sg/impératif"],
  "vit": ["voir", "passé simple 3sg"], "voit": ["voir", "présent 3sg"],
  "verra": ["voir", "futur 3sg"], "voyait": ["voir", "imparfait 3sg"],
  "voient": ["voir", "présent 3pl"], "voyant": ["voir", "participe présent"],
  "pu": ["pouvoir", "participe passé"], "peut": ["pouvoir", "présent 3sg"],
  "pouvait": ["pouvoir", "imparfait 3sg"], "pourra": ["pouvoir", "futur 3sg"],
  "prit": ["prendre", "passé simple 3sg"], "pris": ["prendre", "participe"],
  "prend": ["prendre", "présent 3sg"], "prennent": ["prendre", "présent 3pl"],
  "met": ["mettre", "présent 3sg"], "mit": ["mettre", "passé simple 3sg"],
  "mettra": ["mettre", "futur 3sg"], "mis": ["mettre", "participe"],
  "croit": ["croire", "présent 3sg"], "croira": ["croire", "futur 3sg"],
  "sait": ["savoir", "présent 3sg"], "savait": ["savoir", "imparfait 3sg"],
  "saura": ["savoir", "futur 3sg"], "su": ["savoir", "participe"],
  "veut": ["vouloir", "présent 3sg"], "voulait": ["vouloir", "imparfait 3sg"],
  "voudra": ["vouloir", "futur 3sg"], "veulent": ["vouloir", "présent 3pl"],
  "doit": ["devoir", "présent 3sg"], "devait": ["devoir", "imparfait 3sg"],
  "devra": ["devoir", "futur 3sg"], "doivent": ["devoir", "présent 3pl"],
  "couvrait": ["couvrir", "imparfait 3sg"], "couvre": ["couvrir", "présent 3sg"],
  "couvrira": ["couvrir", "futur 3sg"],
  "déplaçait": ["déplacer", "imparfait 3sg"], "déplace": ["déplacer", "présent 3sg"],
  "déplaça": ["déplacer", "passé simple 3sg"],
  "paraît": ["paraître", "présent 3sg"], "parut": ["paraître", "passé simple 3sg"],
  "paraisse": ["paraître", "subjonctif 3sg"], "paraîtra": ["paraître", "futur 3sg"],
  "produit": ["produire", "participe passé / 3sg"],
  "produise": ["produire", "subjonctif 3sg"],
  "produisant": ["produire", "participe présent"],
  "serve": ["servir", "subjonctif 3sg"], "servent": ["servir", "présent 3pl"],
  "servait": ["servir", "imparfait 3sg"], "servira": ["servir", "futur 3sg"],
  "serviront": ["servir", "futur 3pl"],
  "bénit": ["bénir", "passé simple 3sg"], "bénira": ["bénir", "futur 3sg"],
  "bénissaient": ["bénir", "imparfait 3pl"],
  "meuvent": ["mouvoir", "présent 3pl"], "meut": ["mouvoir", "présent 3sg"],
  "donne": ["donner", "présent 3sg"], "donna": ["donner", "passé simple 3sg"],
  "donnera": ["donner", "futur 3sg"], "domna": ["donner", "futur 3sg"],
  "multiplie": ["multiplier", "présent 3sg"],
  "multiplient": ["multiplier", "présent 3pl"],
  "sépare": ["séparer", "présent 3sg"], "sépara": ["séparer", "passé simple 3sg"],
  "existe": ["exister", "présent 3sg"],
  // --- expanded high-frequency irregular forms ---
  "sommes": ["être", "présent 1pl"], "furent": ["être", "passé simple 3pl"],
  "été": ["être", "participe passé"], "serai": ["être", "futur 1sg"],
  "serons": ["être", "futur 1pl"], "seront": ["être", "futur 3pl"],
  "serez": ["être", "futur 2pl"], "fûtes": ["être", "passé simple 2pl"],
  "sois": ["être", "subjonctif 1sg/2sg"], "seriez": ["être", "conditionnel 2pl"],
  "serais": ["être", "conditionnel 1sg/2sg"],
  "avons": ["avoir", "présent 1pl"], "avez": ["avoir", "présent 2pl"],
  "avais": ["avoir", "imparfait 1sg/2sg"], "aviez": ["avoir", "imparfait 2pl"],
  "eu": ["avoir", "participe passé"], "eurent": ["avoir", "passé simple 3pl"],
  "eus": ["avoir", "passé simple 1sg"], "aurez": ["avoir", "futur 2pl"],
  "aurai": ["avoir", "futur 1sg"], "auront": ["avoir", "futur 3pl"],
  "aurons": ["avoir", "futur 1pl"], "aie": ["avoir", "subjonctif 1sg"],
  "ayant": ["avoir", "participe présent"],
  "veux": ["vouloir", "présent 1sg/2sg"], "voulez": ["vouloir", "présent 2pl"],
  "voulut": ["vouloir", "passé simple 3sg"], "voulurent": ["vouloir", "passé simple 3pl"],
  "voudrait": ["vouloir", "conditionnel 3sg"], "voudraient": ["vouloir", "conditionnel 3pl"],
  "dirent": ["dire", "passé simple 3pl"], "dites": ["dire", "présent 2pl"],
  "disaient": ["dire", "imparfait 3pl"], "diront": ["dire", "futur 3pl"],
  "virent": ["voir", "passé simple 3pl"], "vu": ["voir", "participe passé"],
  "vue": ["voir", "participe passé f."], "vues": ["voir", "participe passé f. pl"],
  "verront": ["voir", "futur 3pl"], "verrez": ["voir", "futur 2pl"],
  "verrai": ["voir", "futur 1sg"],
  "firent": ["faire", "passé simple 3pl"], "faisaient": ["faire", "imparfait 3pl"],
  "feront": ["faire", "futur 3pl"], "ferai": ["faire", "futur 1sg"],
  "viennent": ["venir", "présent 3pl"], "viens": ["venir", "présent 1sg/2sg"],
  "vinrent": ["venir", "passé simple 3pl"], "venu": ["venir", "participe passé"],
  "venus": ["venir", "participe passé pl"], "venue": ["venir", "participe passé f."],
  "venues": ["venir", "participe passé f. pl"], "venant": ["venir", "participe présent"],
  "viendront": ["venir", "futur 3pl"],
  "prendra": ["prendre", "futur 3sg"], "prirent": ["prendre", "passé simple 3pl"],
  "prit": ["prendre", "passé simple 3sg"], "prenaient": ["prendre", "imparfait 3pl"],
  "prenait": ["prendre", "imparfait 3sg"],
  "mirent": ["mettre", "passé simple 3pl"], "mettait": ["mettre", "imparfait 3sg"],
  "mettaient": ["mettre", "imparfait 3pl"], "mettra": ["mettre", "futur 3sg"],
  "répondit": ["répondre", "passé simple 3sg"], "répond": ["répondre", "présent 3sg"],
  "répondra": ["répondre", "futur 3sg"], "répondirent": ["répondre", "passé simple 3pl"],
  "reçu": ["recevoir", "participe passé"], "reçut": ["recevoir", "passé simple 3sg"],
  "reçurent": ["recevoir", "passé simple 3pl"], "reçoit": ["recevoir", "présent 3sg"],
  "reçoivent": ["recevoir", "présent 3pl"], "recevra": ["recevoir", "futur 3sg"],
  "peux": ["pouvoir", "présent 1sg/2sg"], "pouvez": ["pouvoir", "présent 2pl"],
  "puisse": ["pouvoir", "subjonctif 3sg"], "puisses": ["pouvoir", "subjonctif 2sg"],
  "pourraient": ["pouvoir", "conditionnel 3pl"],
  "devenu": ["devenir", "participe passé"], "devenus": ["devenir", "participe passé pl"],
  "devenue": ["devenir", "participe passé f."], "deviendront": ["devenir", "futur 3pl"],
  "sais": ["savoir", "présent 1sg/2sg"], "savez": ["savoir", "présent 2pl"],
  "savent": ["savoir", "présent 3pl"], "saurez": ["savoir", "futur 2pl"],
  "apprit": ["apprendre", "passé simple 3sg"], "appris": ["apprendre", "participe passé / 1sg"],
  "apprirent": ["apprendre", "passé simple 3pl"],
  "cru": ["croire", "participe passé"], "crurent": ["croire", "passé simple 3pl"],
  "croyait": ["croire", "imparfait 3sg"], "croyaient": ["croire", "imparfait 3pl"],
  "écrit": ["écrire", "participe passé / 3sg"], "écrivit": ["écrire", "passé simple 3sg"],
  "écrivirent": ["écrire", "passé simple 3pl"],
  "mourut": ["mourir", "passé simple 3sg"], "moururent": ["mourir", "passé simple 3pl"],
  "meurt": ["mourir", "présent 3sg"], "meurent": ["mourir", "présent 3pl"],
  "vivait": ["vivre", "imparfait 3sg"],
  "vécut": ["vivre", "passé simple 3sg"], "vécurent": ["vivre", "passé simple 3pl"],
  "courut": ["courir", "passé simple 3sg"], "coururent": ["courir", "passé simple 3pl"],
  "naquit": ["naître", "passé simple 3sg"], "naîtra": ["naître", "futur 3sg"],
  "connu": ["connaître", "participe passé"], "connut": ["connaître", "passé simple 3sg"],
  "connurent": ["connaître", "passé simple 3pl"], "connaît": ["connaître", "présent 3sg"],
  "offrit": ["offrir", "passé simple 3sg"], "offert": ["offrir", "participe passé"],
  "sentit": ["sentir", "passé simple 3sg"], "sentait": ["sentir", "imparfait 3sg"],
  "aperçut": ["apercevoir", "passé simple 3sg"], "aperçoit": ["apercevoir", "présent 3sg"],
  "entendit": ["entendre", "passé simple 3sg"], "entendirent": ["entendre", "passé simple 3pl"],
  "entendaient": ["entendre", "imparfait 3pl"], "entendu": ["entendre", "participe passé"],
  "tint": ["tenir", "passé simple 3sg"], "retint": ["retenir", "passé simple 3sg"],
  "retient": ["retenir", "présent 3sg"], "contint": ["contenir", "passé simple 3sg"],
  "battit": ["battre", "passé simple 3sg"], "combattit": ["combattre", "passé simple 3sg"],
  "suivit": ["suivre", "passé simple 3sg"], "suit": ["suivre", "présent 3sg"],
  "suivaient": ["suivre", "imparfait 3pl"], "suivant": ["suivre", "participe présent"],
  "poursuivit": ["poursuivre", "passé simple 3sg"],
  "remit": ["remettre", "passé simple 3sg"], "remis": ["remettre", "participe passé"],
  "permit": ["permettre", "passé simple 3sg"], "permis": ["permettre", "participe passé"],
  "promit": ["promettre", "passé simple 3sg"], "promis": ["promettre", "participe passé"],
  "soumit": ["soumettre", "passé simple 3sg"], "transmit": ["transmettre", "passé simple 3sg"],
  "craignait": ["craindre", "imparfait 3sg"], "craignit": ["craindre", "passé simple 3sg"],
  "craint": ["craindre", "participe passé / 3sg"],
  "haïssait": ["haïr", "imparfait 3sg"], "hait": ["haïr", "présent 3sg"],
  "déclare": ["déclarer", "présent 3sg / 1sg"], "déclara": ["déclarer", "passé simple 3sg"],
  "demanda": ["demander", "passé simple 3sg"], "demandait": ["demander", "imparfait 3sg"],
  "arriva": ["arriver", "passé simple 3sg"], "arrive": ["arriver", "présent 3sg"],
  "arrivent": ["arriver", "présent 3pl"],
  "dût": ["devoir", "passé simple 3sg"],
  "put": ["pouvoir", "passé simple 3sg"],
  // --- second batch: top missing verb forms ---
  "faut": ["falloir", "présent 3sg"], "faudra": ["falloir", "futur 3sg"],
  "faudrait": ["falloir", "conditionnel 3sg"],
  "devez": ["devoir", "présent 2pl"], "dois": ["devoir", "présent 1sg/2sg"],
  "devraient": ["devoir", "conditionnel 3pl"], "devrions": ["devoir", "conditionnel 1pl"],
  "doit": ["devoir", "présent 3sg"],
  "peuvent": ["pouvoir", "présent 3pl"], "pourrez": ["pouvoir", "futur 2pl"],
  "pourrai": ["pouvoir", "futur 1sg"], "peut": ["pouvoir", "présent 3sg"],
  "pourrait": ["pouvoir", "conditionnel 3sg"],
  "vaut": ["valoir", "présent 3sg"], "vaudra": ["valoir", "futur 3sg"],
  "vaudrait": ["valoir", "conditionnel 3sg"],
  "voulu": ["vouloir", "participe passé"],
  "auras": ["avoir", "futur 2sg"],
  "connais": ["connaître", "présent 1sg/2sg"],
  "vienne": ["venir", "subjonctif 3sg"],
  "rend": ["rendre", "présent 3sg"], "rendit": ["rendre", "passé simple 3sg"],
  "rendirent": ["rendre", "passé simple 3pl"], "rendu": ["rendre", "participe passé"],
  "rendra": ["rendre", "futur 3sg"],
  "ordonna": ["ordonner", "passé simple 3sg"], "ordonne": ["ordonner", "présent 3sg"],
  "ordonnèrent": ["ordonner", "passé simple 3pl"],
  "commis": ["commettre", "participe passé"], "commet": ["commettre", "présent 3sg"],
  "commettent": ["commettre", "présent 3pl"],
  "offrit": ["offrir", "passé simple 3sg"], "offert": ["offrir", "participe passé"],
  "offerte": ["offrir", "participe passé f."], "offerts": ["offrir", "participe passé pl"],
  "offrent": ["offrir", "présent 3pl"], "offre": ["offrir", "présent 3sg"],
  "annoncé": ["annoncer", "participe passé"], "annonce": ["annoncer", "présent 3sg"],
  "annonça": ["annoncer", "passé simple 3sg"],
  "tenait": ["tenir", "imparfait 3sg"], "tenaient": ["tenir", "imparfait 3pl"],
  "tiennent": ["tenir", "présent 3pl"],
  "reprit": ["reprendre", "passé simple 3sg"], "reprend": ["reprendre", "présent 3sg"],
  "repondit": ["répondre", "passé simple 3sg"],
  "déclaré": ["déclarer", "participe passé"],
  "décidé": ["décider", "participe passé"], "décide": ["décider", "présent 3sg"],
  "conduisit": ["conduire", "passé simple 3sg"], "conduit": ["conduire", "participe passé / 3sg"],
  "conduire": ["conduire", "infinitif"],
  "agi": ["agir", "participe passé"], "agit": ["agir", "présent 3sg"],
  "accompli": ["accomplir", "participe passé"], "accomplit": ["accomplir", "passé simple 3sg / présent 3sg"],
  "présenta": ["présenter", "passé simple 3sg"], "présente": ["présenter", "présent 3sg"],
  "présenté": ["présenter", "participe passé"],
  "affirma": ["affirmer", "passé simple 3sg"], "affirme": ["affirmer", "présent 3sg"],
  "affirmé": ["affirmer", "participe passé"],
  "passa": ["passer", "passé simple 3sg"], "passe": ["passer", "présent 3sg"],
  "passé": ["passer", "participe passé"],
  "tua": ["tuer", "passé simple 3sg"], "tue": ["tuer", "présent 3sg / participe"],
  "tué": ["tuer", "participe passé"], "tuèrent": ["tuer", "passé simple 3pl"],
  "obtint": ["obtenir", "passé simple 3sg"], "obtiendra": ["obtenir", "futur 3sg"],
  "obtiennent": ["obtenir", "présent 3pl"],
  "attaqua": ["attaquer", "passé simple 3sg"], "attaque": ["attaquer", "présent 3sg"],
  "attaquèrent": ["attaquer", "passé simple 3pl"],
  "accorda": ["accorder", "passé simple 3sg"], "accorde": ["accorder", "présent 3sg"],
  "accordé": ["accorder", "participe passé"],
  "retenue": ["retenir", "participe passé f."],
  "voulait": ["vouloir", "imparfait 3sg"],
  // --- third batch ---
  "vois": ["voir", "présent 1sg/2sg"], "voyez": ["voir", "présent 2pl"],
  "vivent": ["vivre", "présent 3pl"], "vive": ["vivre", "subjonctif 3sg"],
  "mourra": ["mourir", "futur 3sg"], "pourront": ["pouvoir", "futur 3pl"],
  "devaient": ["devoir", "imparfait 3pl"], "tiens": ["tenir", "présent 1sg/2sg"],
  "tient": ["tenir", "présent 3sg"], "jure": ["jurer", "présent 3sg"],
  "désire": ["désirer", "présent 3sg / 1sg"], "désira": ["désirer", "passé simple 3sg"],
  "appartenant": ["appartenir", "participe présent"],
  "adressa": ["adresser", "passé simple 3sg"], "disparaîtra": ["disparaître", "futur 3sg"],
  "déplaît": ["déplaire", "présent 3sg"], "plaît": ["plaire", "présent 3sg"],
  "réservé": ["réserver", "participe passé"], "réserve": ["réserver", "présent 3sg"],
  "réservera": ["réserver", "futur 3sg"],
  "destiné": ["destiner", "participe passé"], "destinée": ["destiner", "participe passé f."],
  // --- fourth batch ---
  "vas": ["aller", "présent 2sg"],
  "serait": ["être", "conditionnel 3sg"], "étiez": ["être", "imparfait 2pl"],
  "étions": ["être", "imparfait 1pl"], "étais": ["être", "imparfait 1sg/2sg"],
  "aurait": ["avoir", "conditionnel 3sg"], "auraient": ["avoir", "conditionnel 3pl"],
  "aurais": ["avoir", "conditionnel 1sg/2sg"],
  "choisis": ["choisir", "participe passé / présent 1sg"], "choisie": ["choisir", "participe passé f."],
  "prenez": ["prendre", "présent 2pl / impératif"] ,
  "mettrai": ["mettre", "futur 1sg"], "rendrai": ["rendre", "futur 1sg"],
  "pourras": ["pouvoir", "futur 2sg"],
  "compris": ["comprendre", "participe passé / présent 1sg"],
  "comprise": ["comprendre", "participe passé f."],
  "permis": ["permettre", "participe passé"], "permise": ["permettre", "participe passé f."],
  "établi": ["établir", "participe passé / présent 3sg"], "établie": ["établir", "participe passé f."],
  "construit": ["construire", "participe passé / 3sg"], "construite": ["construire", "participe passé f."],
  "traité": ["traiter", "participe passé"], "traitée": ["traiter", "participe passé f."],
  "installés": ["installer", "participe passé pl"], "installé": ["installer", "participe passé"],
  "atteint": ["atteindre", "participe passé / 3sg"], "atteinte": ["atteindre", "participe passé f."],
  "refuse": ["refuser", "présent 3sg"], "refusé": ["refuser", "participe passé"],
  "refusant": ["refuser", "participe présent"],
  "succéda": ["succéder", "passé simple 3sg"],
  "enterra": ["enterrer", "passé simple 3sg"], "enterre": ["enterrer", "présent 3sg"],
  // --- fifth batch ---
  "suivi": ["suivre", "participe passé"], "suivie": ["suivre", "participe passé f."],
  "reconnu": ["reconnaître", "participe passé"], "reconnue": ["reconnaître", "participe passé f."],
  "revient": ["revenir", "présent 3sg"], "revinrent": ["revenir", "passé simple 3pl"],
  "appelle": ["appeler", "présent 3sg / 1sg"],
  "préparé": ["préparer", "participe passé"], "préparée": ["préparer", "participe passé f."],
  "révélé": ["révéler", "participe passé"], "révélée": ["révéler", "participe passé f."],
  "convoqua": ["convoquer", "passé simple 3sg"],
  "venaient": ["venir", "imparfait 3pl"],
  "diras": ["dire", "futur 2sg"],
  "concerne": ["concerner", "présent 3sg"],
  "saisit": ["saisir", "passé simple 3sg / présent 3sg"],
  "remplit": ["remplir", "présent 3sg / participe"],
  "rendus": ["rendre", "participe passé pl"], "rendue": ["rendre", "participe passé f."],
  "vivaient": ["vivre", "imparfait 3pl"], "vécu": ["vivre", "participe passé"],
  "descendit": ["descendre", "passé simple 3sg"],
  "s'enfuirent": ["s'enfuir", "passé simple 3pl"], "s'enfuit": ["s'enfuir", "présent 3sg"],
  "mettront": ["mettre", "futur 3pl"],
  "apparut": ["apparaître", "passé simple 3sg"],
  "prise": ["prendre", "participe passé f."], "premie": ["prendre", "subjonctif 1sg"],
  "croient": ["croire", "présent 3pl"],
  "devront": ["devoir", "futur 3pl"], "pouvons": ["pouvoir", "présent 1pl"],
  "construisit": ["construire", "passé simple 3sg"], "construisirent": ["construire", "passé simple 3pl"],
  "devient": ["devenir", "présent 3sg"], "manifeste": ["manifester", "présent 3sg"],
  "ramené": ["ramener", "participe passé"],
  // --- sixth batch ---
  "vivra": ["vivre", "futur 3sg"], "appartiennent": ["appartenir", "présent 3pl"],
  "appartenait": ["appartenir", "imparfait 3sg"],
  "possède": ["posséder", "présent 3sg"], "possédait": ["posséder", "imparfait 3sg"],
  "envoie": ["envoyer", "présent 3sg"], "envoya": ["envoyer", "passé simple 3sg"],
  "reviendra": ["revenir", "futur 3sg"], "reviendrai": ["revenir", "futur 1sg"],
  "concernant": ["concerner", "participe présent"],
  "reçus": ["recevoir", "participe passé pl"], "reçues": ["recevoir", "participe passé f. pl"],
  "déteste": ["détester", "présent 3sg"], "renonce": ["renoncer", "présent 3sg"],
  "confia": ["confier", "passé simple 3sg"], "confié": ["confier", "participe passé"],
  "rends": ["rendre", "présent 1sg/2sg"],
  "disparu": ["disparaître", "participe passé"], "disparus": ["disparaître", "participe passé pl"],
  "permet": ["permettre", "présent 3sg"], "purent": ["pouvoir", "passé simple 3pl"],
  "croyez": ["croire", "présent 2pl"], "voudrais": ["vouloir", "conditionnel 1sg"],
  "s'assit": ["s'asseoir", "passé simple 3sg"],
  "suffit": ["suffire", "présent 3sg"], "posa": ["poser", "passé simple 3sg"],
  "voulaient": ["vouloir", "imparfait 3pl"], "connaissez": ["connaître", "présent 2pl"],
  "sache": ["savoir", "subjonctif 3sg"], "convient": ["convenir", "présent 3sg"],
  "déposa": ["déposer", "passé simple 3sg"], "dressa": ["dresser", "passé simple 3sg"],
  "emmena": ["emmener", "passé simple 3sg"], "voulons": ["vouloir", "présent 1pl"],
  "pouvaient": ["pouvoir", "imparfait 3pl"], "comprenait": ["comprendre", "imparfait 3sg"],
  "bénisse": ["bénir", "subjonctif 3sg"], "devrez": ["devoir", "futur 2pl"],
  "s'inclina": ["s'incliner", "passé simple 3sg"],
  "devinrent": ["devenir", "passé simple 3pl"],
  "dirait": ["dire", "conditionnel 3sg"], "effectue": ["effectuer", "présent 3sg"],
  "sert": ["servir", "présent 3sg"], "offrirez": ["offrir", "futur 2pl"],
  "ouvre": ["ouvrir", "présent 3sg"], "ouvrent": ["ouvrir", "présent 3pl"],
  "suivirent": ["suivre", "passé simple 3pl"], "prendras": ["prendre", "futur 2sg"],
  "mourront": ["mourir", "futur 3pl"], "attend": ["attendre", "présent 3sg"],
  "transmis": ["transmettre", "participe passé / 1sg"],
  "rejette": ["rejeter", "présent 3sg"], "prendront": ["prendre", "futur 3pl"],
  "renvoya": ["renvoyer", "passé simple 3sg"],
  "j'interviendrai": ["intervenir", "futur 1sg"],
  "tiré": ["tirer", "participe passé"], "tire": ["tirer", "présent 3sg"],
  "saisis": ["saisir", "participe passé / 1sg"],
  "attendant": ["attendre", "participe présent"],
  "achevé": ["achever", "participe passé"],
  "étendu": ["étendre", "participe passé"],
  "considère": ["considérer", "présent 3sg"], "conclu": ["conclure", "participe passé"],
  "ressemble": ["ressembler", "présent 3sg"],
  "apparu": ["apparaître", "participe passé"],
  // --- seventh batch ---
  "tenu": ["tenir", "participe passé"], "tenue": ["tenir", "participe passé f."],
  "entend": ["entendre", "présent 3sg"], "entends": ["entendre", "présent 1sg/2sg"],
  "désobéi": ["désobéir", "participe passé"], "désobéit": ["désobéir", "présent 3sg"],
  "rendent": ["rendre", "présent 3pl"], "rendes": ["rendre", "subjonctif 2sg"],
  "supplie": ["supplier", "présent 3sg / 1sg"],
  "conclue": ["conclure", "participe passé f."],
  "remercie": ["remercier", "présent 3sg / 1sg"],
  "jette": ["jeter", "présent 3sg"], "jettent": ["jeter", "présent 3pl"],
  "reviennent": ["revenir", "présent 3pl"], "suivent": ["suivre", "présent 3pl"],
  // --- eighth batch ---
  "conduits": ["conduire", "participe passé pl"], "conduites": ["conduire", "participe passé f. pl"],
  "puissent": ["pouvoir", "subjonctif 3pl"],
  "disais": ["dire", "imparfait 1sg/2sg"],
  "ouvert": ["ouvrir", "participe passé"], "ouverte": ["ouvrir", "participe passé f."],
  "connaissent": ["connaître", "présent 3pl"],
  "vante": ["vanter", "présent 3sg"], "répliqua": ["répliquer", "passé simple 3sg"],
  "pourrais": ["pouvoir", "conditionnel 1sg/2sg"],
  "pourrais-je": ["pouvoir", "conditionnel 1sg"],
};

// -er conjugation suffixes -> tense (ordered longest-first; port of _ER_RULES).
const _ER_RULES = [
  ["ées$", "participle f. pl"], ["és$", "participle m. pl"],
  ["ée$", "participle f. sg"], ["é$", "past participle"],
  ["eront$", "futur 3pl"], ["erons$", "futur 1pl"],
  ["erez$", "futur 2pl"], ["eras$", "futur 2sg"],
  ["era$", "futur 3sg"], ["erai$", "futur 1sg"],
  ["aient$", "imparfait 3pl"], ["iez$", "imparfait 2pl"],
  ["ions$", "imparfait 1pl"], ["ait$", "imparfait 3sg"],
  ["ais$", "imparfait 1/2sg"],
  ["èrent$", "passé simple 3pl"], ["âtes$", "passé simple 2pl"],
  ["âmes$", "passé simple 1pl"], ["à$", "passé simple 3sg"],
  ["â$", "passé simple 3sg"],
  ["ons$", "présent 1pl"], ["ez$", "présent 2pl"],
  ["ent$", "présent 3pl"],
  ["a$", "passé simple 3sg"],
  ["es$", "présent 2sg"], ["e$", "présent 1/3sg"],
];

// -ir rules (port of _IR_RULES).
const _IR_RULES = [
  ["issant$", "participle"], ["ie?nt$", "présent 3pl"],
  ["issons$", "présent 1pl"], ["issez$", "présent 2pl"],
  ["irent$", "passé simple 3pl"],
  ["it$", "présent/ passé simple 3sg"],
  ["i$", "participe passé"],
];

function _stripElisions(word) {
  return word.replace(/[’']/g, "");
}

function verbInfinitive(word) {
  const f = word.toLowerCase().replace(/[’‘]/g, "'");
  if (_VERB_IRREGULAR[f]) {
    return [_VERB_IRREGULAR[f].slice()];
  }
  const w = _stripElisions(f);
  const out = [];
  // -er verbs (longest suffix first; only the first -er match shapes the base)
  for (const [re, tense] of _ER_RULES) {
    const m = new RegExp(re).exec(w);
    if (m) {
      const base = w.slice(0, m.index);
      if (base) out.push([base + "er", tense]);
      break;
    }
  }
  // -ir verbs
  for (const [re, tense] of _IR_RULES) {
    const m = new RegExp(re).exec(w);
    if (m) {
      const base = w.slice(0, m.index);
      if (base && (re !== "it$" || !/[lnr]$/.test(base))) {
        out.push([base + "ir", tense]);
      }
    }
  }
  // -re verbs: past participles in -u (attendu -> attendre, rendu -> rendre, ...)
  if (/u$/.test(w) && w.length > 3) {
    out.push([w.slice(0, -1) + "re", "participe passé"]);
  }
  return out;
}

// ---- friendly explanations of tense / form labels -------------------------
const _TENSE_FR = {
  "présent": "presente (algo que ocurre ahora)",
  "imparfait": "pasado incompleto (describía hábitos o acciones en curso)",
  "passé simple": "pasado simple (una acción concreta y terminada)",
  "futur": "futuro (ocurrirá)",
  "subjonctif": "subjuntivo (deseo, duda o emoción)",
  "impératif": "imperativo (una orden)",
};

const _PARTICIPLE_FR = {
  "past participle": "participio pasado («-ado / -ido»)",
  "participe": "participio",
  "participle": "participio",
  "participe passé": "participio pasado («-ado / -ido»)",
  "participle f. sg": "participio pasado, femenino singular («-ada»)",
  "participle m. pl": "participio pasado, masculino plural («-ados»)",
  "participle f. pl": "participio pasado, femenino plural («-adas»)",
  "participe présent": "participio presente («-ando / -iendo»)",
  "participle présent": "participio presente («-ando / -iendo»)",
};

const _PERSON_FR = {
  "1sg": "1.ª persona del singular (yo)",
  "2sg": "2.ª persona del singular (tú)",
  "3sg": "3.ª persona del singular (él / ella)",
  "1pl": "1.ª persona del plural (nosotros / nosotras)",
  "2pl": "2.ª persona del plural (ustedes)",
  "3pl": "3.ª persona del plural (ellos / ellas)",
  "1/2sg": "1.ª o 2.ª persona del singular (yo / tú)",
};

function friendlyTense(label) {
  if (!label) return "";
  label = String(label).trim();
  let person = "";
  const m = label.match(/\b(1\/2sg|1sg|2sg|3sg|1pl|2pl|3pl)\b/);
  if (m) {
    person = _PERSON_FR[m[1]] || m[1];
    label = label.slice(0, m.index) + label.slice(m.index + m[0].length);
  }
  label = label.trim().replace(/^[,;\·\/\s]+|[,;\·\/\s]+$/g, "");
  const names = [];
  for (const part of label.split("/")) {
    const p = part.trim();
    if (!p) continue;
    const low = p.toLowerCase();
    if (_PARTICIPLE_FR[low]) names.push(_PARTICIPLE_FR[low]);
    else if (_TENSE_FR[low]) names.push(_TENSE_FR[low]);
    else names.push(p);
  }
  let text = names.length ? names.join(" o ") : label;
  if (person) text = text ? `${text} · ${person}` : person;
  return text;
}

function friendlyForm(label) {
  if (!label) return "";
  label = String(label).trim();
  let m = label.match(/^plural de «(.+)»$/);
  if (m) {
    return `es el plural de «${m[1]}» — se refiere a varias personas o cosas`;
  }
  m = label.match(/^«(.+)-…»\s*\(forma compuesta\)$/);
  if (m) {
    return `es una forma compuesta: el verbo «${m[1]}» con un pronombre unido (p. ej. «${m[1]}-la» = «${m[1]}» + «la»)`;
  }
  return label;
}

// ---- Dictionary class -----------------------------------------------------
class Dictionary {
  constructor(map) {
    this._map = map;
    // accent-preserving index of the raw dict (the normalize() key strips accents,
    // so accented entries in dict.json are otherwise unreachable)
    this._accent = new Map();
    for (const [key, val] of Object.entries(map)) {
      this._accent.set(String(key).toLowerCase().replace(/[’‘]/g, "'"), val);
    }
    // layer curated overlays (mirroring the python __init__ merge)
    for (const [key, val] of Object.entries(_CURATED)) {
      const k = normalize(key);
      if (!this._map[k]) this._map[k] = [];
      if (val && !this._map[k].includes(val)) this._map[k].push(val);
    }
    for (const [key, val] of Object.entries(_COMMON_VERBS)) {
      const k = normalize(key);
      if (!this._map[k]) this._map[k] = [];
      if (val && !this._map[k].includes(val)) this._map[k].push(val);
    }
    for (const [key, val] of Object.entries(_COMMON_NOUNS)) {
      const k = normalize(key);
      if (!this._map[k]) this._map[k] = [];
      if (val && !this._map[k].includes(val)) this._map[k].push(val);
    }
    for (const [key, val] of Object.entries(_EXTRA_WORDS)) {
      const k = normalize(key);
      if (!this._map[k]) this._map[k] = [];
      if (val && !this._map[k].includes(val)) this._map[k].push(val);
    }
    for (const [key, val] of Object.entries(_BIBLE_WORDS)) {
      const k = normalize(key);
      if (!this._map[k]) this._map[k] = [];
      if (val && !this._map[k].includes(val)) this._map[k].push(val);
    }
    for (const [key, val] of Object.entries(_BIBLE_NAMES)) {
      const k = normalize(key);
      if (!this._map[k]) this._map[k] = [];
      if (val && !this._map[k].includes(val)) this._map[k].push(val);
    }
  }

  lookup(word) {
    const arr = this._map[normalize(word)];
    return arr ? arr.slice() : null;
  }

  static _singular(word) {
    const low = word.toLowerCase();
    if (low.endsWith("eaux")) return word.slice(0, -1);
    if (low.endsWith("aux")) return word.slice(0, -3) + "al";
    if (low.endsWith("oux")) return word.slice(0, -3) + "ou";
    if (low.endsWith("eux")) {
      if (low === "yeux") return "oeil";
      return word.slice(0, -3) + "eu";
    }
    if (low.endsWith("s") && !/(ss|us|is|as|os)$/.test(low)) return word.slice(0, -1);
    if (low.endsWith("x") && !/(aux|eaux|oux|eux)$/.test(low)) return word.slice(0, -1);
    return word;
  }

  resolve(word) {
    const info = {};
    // strip elided contractions (l', d', n', s', qu', jusqu', etc.)
    const elide = /^(?:qu|jusqu|lorsqu|puisqu|quoiqu|aujourd|[ldqnsjcmt])[’']/i;
    let candidates = [word];
    const m = elide.exec(word);
    if (m) candidates.push(word.slice(m[0].length));
    for (const cand of candidates) {
      const res = this._tryDirect(cand, info);
      if (res) return res;
      for (const [inf, tense] of verbInfinitive(cand)) {
        const meanings = this.lookup(inf);
        if (meanings) {
          info.infinitive = inf;
          info.tense = tense || "";
          return [meanings, info];
        }
      }
    }
    // hyphenated forms (impératif + pronom, e.g. "dominez-la")
    if (word.includes("-")) {
      const left = word.split("-")[0];
      const [m2, info2] = this.resolve(left);
      if (m2) {
        info.form = `«${left}-…» (forma compuesta)`;
        Object.assign(info, info2);
        return [m2, info];
      }
    }
    // accent-stripped fallback
    for (const variant of [word, m ? word.slice(m[0].length) : word]) {
      const variants = [normalize(variant), variant.charAt(0).toUpperCase() + variant.slice(1),
                        normalize(variant.charAt(0).toUpperCase() + variant.slice(1))];
      for (const v2 of variants) {
        const meanings = this.lookup(v2);
        if (meanings) return [meanings, info];
      }
      // last resort: exact accented key in the raw dict (lookup() strips accents)
      const acc = this._accent.get(variant.toLowerCase().replace(/[’‘]/g, "'"));
      if (acc) return [acc.slice(), info];
    }
    return [null, info];
  }

  _tryDirect(cand, info) {
    const m = this.lookup(cand);
    if (m) return [m, info];
    const sing = Dictionary._singular(cand);
    if (sing !== cand) {
      const meanings = this.lookup(sing);
      if (meanings) {
        info.form = `plural de «${sing}»`;
        return [meanings, info];
      }
    }
    return null;
  }

  segment(text) {
    const words = [];
    for (const tok of text.split(/\s+/)) {
      const w = tok.replace(/^[.,;:!?«»"'“”‘’\[\]()*–—]+|[.,;:!?«»"'“”‘’\[\]()*–—]+$/g, "");
      if (w && !/^\d+$/.test(w)) words.push(w);
    }
    const out = [];
    let i = 0;
    while (i < words.length) {
      let best = null;
      for (let length = words.length - i; length > 1; length--) {
        const cand = words.slice(i, i + length).join(" ");
        const [m, info] = this.resolve(cand);
        if (m) { best = [length, cand, m, info]; break; }
      }
      if (best) {
        out.push([best[1], best[2], best[3]]);
        i += best[0];
      } else {
        const cand = words[i];
        const [m, info] = this.resolve(cand);
        out.push([cand, m, info]);
        i += 1;
      }
    }
    return out;
  }
}

export { Dictionary, normalize, friendlyTense, friendlyForm };
